global_costmap: 
   global_frame: map
   robot_base_frame: base_footprint
   update_frequency: 7.0
   publish_frequency: 2.0
   static_map: true
   rolling_window: false
   resolution: 0.05
   map_type: costmap
   transform_tolerance: 1   #配置转换的最大延迟
   planner_frequency: 10.0        #配置规划循化的频率
   planner_patiente: 2.0         #配置规划器寻找一条有效路径的等待时间

